In [1]:
import pandas as pd
from collections import Counter

filepath = './../data/dataset_site_info.parquet'
df = pd.read_parquet(filepath)

In [2]:
def get_process(name):
    string = name.replace('/', ' ').replace('_', ' ')
    process = string.split()[0]
    return process

In [3]:
df['process'] = df['dataset_name'].apply(get_process)

In [4]:
df_aod = df[df['tier'] == 'AOD']

print('number of distinct AOD datasets =', df_aod['dataset_name'].nunique())
print('number of distinct AOD physics processes =', df_aod['process'].nunique())

df_aod.head()

number of distinct AOD datasets = 4407
number of distinct AOD physics processes = 370

,dataset_name,dataset_id,replica_time_create,node_name,rep_size,min_time,max_time,br_user_group_id,tier,process
0,/JetHT/Run2016B-21Feb2020_ver2_UL2016_HIPM-v1/AOD,1553410,20200619,T2_US_Purdue,2.570957e+10,2020-06-20,2020-12-31,42.0,AOD,JetHT
1,/PAMinimumBias4/PARun2016C-PromptReco-v1/AOD,951505,20171015,T2_IN_TIFR,2.668056e+13,2019-01-01,2020-06-10,42.0,AOD,PAMinimumBias4
4,/HLTPhysics/Commissioning2017-PromptReco-v1/AOD,998897,20200212,T2_EE_Estonia,1.705387e+11,2020-02-13,2020-03-25,42.0,AOD,HLTPhysics
6,/HIMinimumBiasReducedFormat3/HIRun2018-PromptR...,1233190,20181107,T2_US_Vanderbilt,1.077554e+09,2019-01-01,2020-12-31,42.0,AOD,HIMinimumBiasReducedFormat3
10,/SingleMuon/Run2017F-17Nov2017-v1/AOD,1098977,20181215,T2_BE_IIHE,7.943913e+13,2019-01-01,2019-06-15,42.0,AOD,SingleMuon

In [5]:
df_aodsim = df[df['tier'] == 'AODSIM']

print('number of distinct AODSIM datasets =', df_aodsim['dataset_name'].nunique())
print('number of distinct AODSIM physics processes =', df_aodsim['process'].nunique())

df_aodsim.head()

number of distinct AODSIM datasets = 46339
number of distinct AODSIM physics processes = 1975

,dataset_name,dataset_id,replica_time_create,node_name,rep_size,min_time,max_time,br_user_group_id,tier,process
2,/GluGluToContinToZZTo2mu2nu_13TeV_MCFM701_pyth...,1114967,20200113,T2_FI_HIP,2.060427e+11,2020-01-14,2020-04-29,42.0,AODSIM,GluGluToContinToZZTo2mu2nu
3,/WJetsToLNu_HT-70To100_TuneCP5_13TeV-madgraphM...,1247050,20200323,T2_US_Caltech,1.034198e+13,2020-03-23,2020-05-05,22.0,AODSIM,WJetsToLNu
5,/SMS-T2bt-LLChipm_ctau-200_mLSP-1400_TuneCUETP...,1397254,20190925,T2_DE_DESY,1.866242e+11,2019-09-26,2020-12-31,22.0,AODSIM,SMS-T2bt-LLChipm
7,/DYJetsToMuMu_M-50_TuneCP5_14TeV-madgraphMLM-p...,1560259,20200524,T1_RU_JINR_Disk,1.618496e+12,2020-06-06,2020-09-29,18.0,AODSIM,DYJetsToMuMu
8,/DYJetsToTauTau_ForcedMuDecay_M-50_TuneCP5_13T...,1106693,20181003,T2_FR_IPHC,5.941757e+11,2019-01-01,2019-02-13,42.0,AODSIM,DYJetsToTauTau

In [6]:
process_count_aod = Counter(df_aod.drop_duplicates(subset=['dataset_name'])['process'])

process_count_aod.most_common(20)

[('HLTPhysicsIsolatedBunch', 337),
 ('DoubleMuon', 242),
 ('NoBPTX', 242),
 ('BTag', 241),
 ('DoubleElectron', 240),
 ('ZeroBias', 137),
 ('JetHT', 129),
 ('SingleMuon', 117),
 ('MET', 94),
 ('Charmonium', 81),
 ('MinimumBias', 78),
 ('DoubleEG', 67),
 ('MuOnia', 67),
 ('HLTPhysics', 66),
 ('SingleElectron', 66),
 ('MuonEG', 64),
 ('Tau', 64),
 ('BTagMu', 60),
 ('HcalNZS', 60),
 ('Cosmics', 55)]

In [7]:
process_count_aodsim = Counter(df_aodsim.drop_duplicates(subset=['dataset_name'])['process'])

process_count_aodsim.most_common(20)

[('QCD', 1419),
 ('ggH', 1368),
 ('SeesawTypeIII', 1208),
 ('RelValProdMinBias', 1052),
 ('BlackHole', 1044),
 ('VBF', 831),
 ('DYJetsToLL', 792),
 ('gluinoGMSB', 677),
 ('ST', 576),
 ('DarkMatter', 552),
 ('BprimeJetToBZ', 452),
 ('WpToBpT', 420),
 ('WpToTpB', 416),
 ('ZH', 390),
 ('MSSMD', 381),
 ('DisplacedSUSY', 378),
 ('BuToJpsiKV2', 344),
 ('ADDGravToGG', 333),
 ('QDTojWinc', 328),
 ('WplusH', 315)]